version: "3.9"
services:
  
  db:
    image: postgres:14.7-alpine
    container_name: postgress
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zedenga
      - POSTGRES_DB=larazillow
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres
    container_name: postgress
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=larazillow
      - DB_USERNAME=postgres
      - DB_PASSWORD=zedenga
    depends_on:
      - db
    networks:
      - app-network

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      ports:
       - "5050:80"
      depends_on:
       - db
      environment:
       PGADMIN_DEFAULT_EMAIL: melckzedeck063@gmail.com
       PGADMIN_DEFAULT_PASSWORD: password

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge